# Generated by Django 2.2.6 on 2019-10-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
