# Generated by Django 2.2.6 on 2019-10-23 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MTP', '0002_auto_20191023_0934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dummyclass',
        ),
        migrations.DeleteModel(
            name='dummysss',
        ),
    ]
