# Generated by Django 2.2.6 on 2019-10-23 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MTP', '0003_auto_20191023_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=10000)),
                ('tid_list', models.CharField(max_length=20000, null=True)),
                ('option1', models.CharField(max_length=1000, null=True)),
                ('option2', models.CharField(max_length=1000, null=True)),
                ('option3', models.CharField(max_length=1000, null=True)),
                ('option4', models.CharField(max_length=1000, null=True)),
                ('option5', models.CharField(max_length=1000, null=True)),
                ('correct', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='faculty',
            name='lname',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='lname',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='co_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MTP.Course'),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=40)),
                ('qid_list', models.CharField(max_length=20000, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MTP.Faculty')),
            ],
        ),
    ]
