# Generated by Django 2.2.6 on 2019-10-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTP', '0004_auto_20191023_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='admin',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
