# Generated by Django 2.2.6 on 2019-10-31 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTP', '0005_faculty_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='co_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
