# Generated by Django 2.2.6 on 2019-10-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTP', '0006_auto_20191031_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='co_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='sub_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='test_name',
            field=models.CharField(max_length=100),
        ),
    ]
