# Generated by Django 2.2.6 on 2019-10-31 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MTP', '0007_auto_20191031_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='created_by',
        ),
    ]
